fix: pre-push git hook not working properly

diff --git a/{{cookiecutter.project_name}}/hooks/pre-push b/{{cookiecutter.project_name}}/hooks/pre-push
--- a/{{cookiecutter.project_name}}/hooks/pre-push
+++ b/{{cookiecutter.project_name}}/hooks/pre-push
@@ -2,3 +2,12 @@
 
 echo "Running pre-push hook"
 docker-compose -f docker-compose.tests.yml up tests
+
+# Check the exit status of the tests
+if docker-compose -f docker-compose.tests.yml logs tests | tail -n 1 | grep -E "= \d+ passed(, \d+ warnings?)? in \d+\.\d{2}s ="; then
+    echo "Tests passed. Proceeding with push."
+    exit 0
+fi
+
+echo "Tests failed. Aborting push."
+exit 1
